### ISSUE TITLE
"Update" command do not update map

### ISSUE THREAD

**Issue by Self-Perfection** [RomanGolovanov/ametro#134]
I observe this on version 2.0.1.5 from F-Droid with Moscow map.

Moscow map got drastically updated recently after new subway line became operational. There is updated map on pMetro project website but "update" command in aMetro app do not download new map.

There is workaround: delete all Moscow metro maps from aMetro and download map from scratch.

[Related discussion at 4PDA](http://4pda.ru/forum/index.php?s=&showtopic=171437&view=findpost&p=53333183)

**Comment by RomanGolovanov** [comment]
outdated. autoupdate not work because its support was canceled by maps owner.
